project:
  type: website

website:
  title: "Experimenting with LLMs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sque-oats
format:
  html:
    theme: morph
    css: styles.css

execute:
  freeze: auto


